# Generated by Django 5.1.5 on 2025-07-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_u_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='u_email',
            field=models.EmailField(default='default@gmail.com', max_length=20),
        ),
    ]
